-- SQL setup for Adatech CMS
CREATE DATABASE IF NOT EXISTS adatech_cms DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE adatech_cms;

-- Content (landing, about, contact)
CREATE TABLE IF NOT EXISTS content (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(32) NOT NULL, -- 'landing', 'about', 'contact'
  title VARCHAR(255),
  body TEXT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Team
CREATE TABLE IF NOT EXISTS team (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  role VARCHAR(128),
  bio TEXT,
  image VARCHAR(255),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Testimonials
CREATE TABLE IF NOT EXISTS testimonials (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  role VARCHAR(128),
  message TEXT,
  image VARCHAR(255),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Services
CREATE TABLE IF NOT EXISTS services (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(128) NOT NULL,
  description TEXT,
  icon VARCHAR(64),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Projects
CREATE TABLE IF NOT EXISTS projects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(128) NOT NULL,
  description TEXT,
  image VARCHAR(255),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Images (logo, etc.)
CREATE TABLE IF NOT EXISTS images (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(32) NOT NULL, -- 'logo', 'team', 'project', etc.
  filename VARCHAR(255) NOT NULL,
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Blog posts
CREATE TABLE IF NOT EXISTS posts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE,
  excerpt TEXT,
  body TEXT,
  image VARCHAR(255),
  author VARCHAR(128),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ==================================================================
-- Extended schema: add optional useful columns used by the PHP code
-- NOTE: The following ALTER statements use `ADD COLUMN IF NOT EXISTS` (MySQL 8+).
-- If your MySQL version is older (5.7), either remove the `IF NOT EXISTS`
-- parts and run carefully, or run the commented fallback ALTERs below them.
-- Run this file with your DB client (phpMyAdmin / mysql CLI). Back up DB first.
-- ==================================================================

-- CONTENT: add meta, slug, status, created_at
ALTER TABLE content ADD COLUMN IF NOT EXISTS slug VARCHAR(255) DEFAULT NULL;
ALTER TABLE content ADD COLUMN IF NOT EXISTS meta_title VARCHAR(255) DEFAULT NULL;
ALTER TABLE content ADD COLUMN IF NOT EXISTS meta_description VARCHAR(255) DEFAULT NULL;
ALTER TABLE content ADD COLUMN IF NOT EXISTS status ENUM('published','draft') DEFAULT 'published';
ALTER TABLE content ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NULL DEFAULT NULL;

-- IMAGES: store path, alt text, caption, folder, width/height, registered flag
ALTER TABLE images ADD COLUMN IF NOT EXISTS path VARCHAR(255) DEFAULT NULL;
ALTER TABLE images ADD COLUMN IF NOT EXISTS alt VARCHAR(255) DEFAULT NULL;
ALTER TABLE images ADD COLUMN IF NOT EXISTS caption TEXT DEFAULT NULL;
ALTER TABLE images ADD COLUMN IF NOT EXISTS folder VARCHAR(128) DEFAULT NULL;
ALTER TABLE images ADD COLUMN IF NOT EXISTS width INT DEFAULT NULL;
ALTER TABLE images ADD COLUMN IF NOT EXISTS height INT DEFAULT NULL;
ALTER TABLE images ADD COLUMN IF NOT EXISTS filesize BIGINT DEFAULT NULL;
ALTER TABLE images ADD COLUMN IF NOT EXISTS registered TINYINT(1) DEFAULT 1;
ALTER TABLE images ADD COLUMN IF NOT EXISTS uploaded_by VARCHAR(128) DEFAULT NULL;

-- TEAM: alt text for images
ALTER TABLE team ADD COLUMN IF NOT EXISTS image_alt VARCHAR(255) DEFAULT NULL;

-- TESTIMONIALS: add fields author, company, quote, visible
ALTER TABLE testimonials ADD COLUMN IF NOT EXISTS author VARCHAR(128) DEFAULT NULL;
ALTER TABLE testimonials ADD COLUMN IF NOT EXISTS company VARCHAR(128) DEFAULT NULL;
ALTER TABLE testimonials ADD COLUMN IF NOT EXISTS quote TEXT DEFAULT NULL;
ALTER TABLE testimonials ADD COLUMN IF NOT EXISTS visible TINYINT(1) DEFAULT 1;

-- PROJECTS: add excerpt, image_alt, category
ALTER TABLE projects ADD COLUMN IF NOT EXISTS excerpt TEXT DEFAULT NULL;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS image_alt VARCHAR(255) DEFAULT NULL;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS category VARCHAR(128) DEFAULT NULL;

-- SERVICES: add excerpt, image, image_alt
ALTER TABLE services ADD COLUMN IF NOT EXISTS excerpt TEXT DEFAULT NULL;
ALTER TABLE services ADD COLUMN IF NOT EXISTS image VARCHAR(255) DEFAULT NULL;
ALTER TABLE services ADD COLUMN IF NOT EXISTS image_alt VARCHAR(255) DEFAULT NULL;

ALTER TABLE posts ADD COLUMN IF NOT EXISTS status ENUM('published','draft') DEFAULT 'published';
ALTER TABLE posts ADD COLUMN IF NOT EXISTS published_at TIMESTAMP NULL DEFAULT NULL;
-- Add attached references for images and image field for content
ALTER TABLE images ADD COLUMN IF NOT EXISTS attached_type VARCHAR(32) DEFAULT NULL;
ALTER TABLE images ADD COLUMN IF NOT EXISTS attached_id INT DEFAULT NULL;
ALTER TABLE content ADD COLUMN IF NOT EXISTS image VARCHAR(255) DEFAULT NULL;

/*
Fallback (MySQL < 8.0): Uncomment and run the following ALTERs only
if `ADD COLUMN IF NOT EXISTS` is not supported. Run each ALTER only if
you confirm the column doesn't already exist to avoid errors.

-- ALTER TABLE content ADD COLUMN slug VARCHAR(255) DEFAULT NULL;
-- ALTER TABLE content ADD COLUMN meta_title VARCHAR(255) DEFAULT NULL;
-- ALTER TABLE content ADD COLUMN meta_description VARCHAR(255) DEFAULT NULL;
-- ALTER TABLE content ADD COLUMN status ENUM('published','draft') DEFAULT 'published';
-- ALTER TABLE content ADD COLUMN created_at TIMESTAMP NULL DEFAULT NULL;

-- ALTER TABLE images ADD COLUMN path VARCHAR(255) DEFAULT NULL;
-- ALTER TABLE images ADD COLUMN alt VARCHAR(255) DEFAULT NULL;
-- ALTER TABLE images ADD COLUMN caption TEXT DEFAULT NULL;
-- ALTER TABLE images ADD COLUMN folder VARCHAR(128) DEFAULT NULL;
-- ALTER TABLE images ADD COLUMN width INT DEFAULT NULL;
-- ALTER TABLE images ADD COLUMN height INT DEFAULT NULL;
-- ALTER TABLE images ADD COLUMN filesize BIGINT DEFAULT NULL;
-- ALTER TABLE images ADD COLUMN registered TINYINT(1) DEFAULT 1;
-- ALTER TABLE images ADD COLUMN uploaded_by VARCHAR(128) DEFAULT NULL;

-- ALTER TABLE team ADD COLUMN image_alt VARCHAR(255) DEFAULT NULL;

-- ALTER TABLE testimonials ADD COLUMN author VARCHAR(128) DEFAULT NULL;
-- ALTER TABLE testimonials ADD COLUMN company VARCHAR(128) DEFAULT NULL;
-- ALTER TABLE testimonials ADD COLUMN quote TEXT DEFAULT NULL;
-- ALTER TABLE testimonials ADD COLUMN visible TINYINT(1) DEFAULT 1;

-- ALTER TABLE projects ADD COLUMN excerpt TEXT DEFAULT NULL;
-- ALTER TABLE projects ADD COLUMN image_alt VARCHAR(255) DEFAULT NULL;
-- ALTER TABLE projects ADD COLUMN category VARCHAR(128) DEFAULT NULL;

-- ALTER TABLE services ADD COLUMN excerpt TEXT DEFAULT NULL;
-- ALTER TABLE services ADD COLUMN image VARCHAR(255) DEFAULT NULL;
-- ALTER TABLE services ADD COLUMN image_alt VARCHAR(255) DEFAULT NULL;

-- ALTER TABLE posts ADD COLUMN status ENUM('published','draft') DEFAULT 'published';
-- ALTER TABLE posts ADD COLUMN published_at TIMESTAMP NULL DEFAULT NULL;
*/