<?php
// admin/manage_site_images.php
session_start();
if (!isset($_SESSION['admin_logged_in']) || $_SESSION['admin_logged_in'] !== true) {
    header('Location: index.php');
    exit;
}

require_once __DIR__ . '/../includes/db.php';
require_once __DIR__ . '/../includes/helpers.php';
require_once __DIR__ . '/../includes/upload.php';
require_once __DIR__ . '/../includes/site_images.php';

$message = '';
$error = '';

// Ensure upload target dir for site images exists
$siteDir = __DIR__ . '/../assets/img/site';
if (!file_exists($siteDir)) @mkdir($siteDir, 0755, true);

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    try {
        $action = $_POST['action'] ?? 'save';
        $key = $_POST['key'] ?? '';
        if (!$key) throw new RuntimeException('Missing key');

        // If a file uploaded for this key, save it to assets/img/site and create/update local overrides
        if (!empty($_FILES['image']) && $_FILES['image']['error'] !== UPLOAD_ERR_NO_FILE) {
            $uploaded = handle_image_upload('image', $siteDir);
            // uploaded returns a web path relative to project; convert to a path without leading slash
            $rel = ltrim($uploaded, '/\\');
            // Prepare overrides array
            $localFile = __DIR__ . '/../includes/site_images.local.php';
            $overrides = [];
            if (is_file($localFile)) {
                $maybe = include $localFile;
                if (is_array($maybe)) $overrides = $maybe;
            }
            $overrides[$key] = $rel;
            $out = '<?php\n// Auto-generated by admin/manage_site_images.php - do not commit unless intended\nreturn ' . var_export($overrides, true) . ';\n';
            file_put_contents($localFile, $out, LOCK_EX);
            $message = 'Image uploaded and override saved for ' . htmlspecialchars($key);
        } else {
            // Manual value (text) update
            $val = trim($_POST['value'] ?? '');
            $localFile = __DIR__ . '/../includes/site_images.local.php';
            $overrides = [];
            if (is_file($localFile)) {
                $maybe = include $localFile;
                if (is_array($maybe)) $overrides = $maybe;
            }
            if ($val === '') {
                // remove override
                unset($overrides[$key]);
            } else {
                $overrides[$key] = ltrim($val, '/\\');
            }
            $out = '<?php\n// Auto-generated by admin/manage_site_images.php - do not commit unless intended\nreturn ' . var_export($overrides, true) . ';\n';
            file_put_contents($localFile, $out, LOCK_EX);
            $message = 'Override saved for ' . htmlspecialchars($key);
        }
    } catch (Exception $e) {
        $error = $e->getMessage();
    }
}

// Re-load site images (global $SITE_IMAGES is defined in includes/site_images.php)
// include again to ensure local overrides are picked up
include __DIR__ . '/../includes/site_images.php';

// Prepare keys list
$keys = array_keys($SITE_IMAGES);

require_once __DIR__ . '/partials/header.php';
?>
<style>.site-image-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:12px}.site-image-card{border:1px solid #e9ecef;padding:10px;border-radius:6px;background:#fff}.site-image-card img{max-width:100%;height:120px;object-fit:cover}</style>
<div class="container">
  <h2>Manage Site Images</h2>
  <?php if ($message): ?><div class="msg"><?php echo esc($message); ?></div><?php endif; ?>
  <?php if ($error): ?><div class="error"><?php echo esc($error); ?></div><?php endif; ?>

  <p>Upload a file to replace a key, or enter a relative path (e.g. <code>assets/img/custom/foo.jpg</code>).</p>

  <div class="site-image-grid">
    <?php foreach ($keys as $k):
      $url = site_image($k);
      $localVal = null;
      $localFile = __DIR__ . '/../includes/site_images.local.php';
      if (is_file($localFile)) {
        $maybe = include $localFile; if (is_array($maybe) && isset($maybe[$k])) $localVal = $maybe[$k];
      }
    ?>
      <div class="site-image-card">
        <h4><?php echo esc($k); ?></h4>
        <div style="margin-bottom:8px"><img src="<?php echo esc($url); ?>" alt=""></div>
        <form action="manage_site_images.php" method="post" enctype="multipart/form-data">
          <input type="hidden" name="key" value="<?php echo esc($k); ?>">
          <div><label>Upload file<br><input type="file" name="image" accept="image/*"></label></div>
          <div style="margin-top:6px"><button type="submit">Upload & Save</button></div>
        </form>
        <form action="manage_site_images.php" method="post" style="margin-top:8px">
          <input type="hidden" name="key" value="<?php echo esc($k); ?>">
          <div><label>Or set path<br>
            <div style="display:flex;gap:8px;align-items:center">
              <input id="value-<?php echo esc($k); ?>" type="text" name="value" value="<?php echo esc($localVal ?? ''); ?>" style="flex:1">
              <button type="button" class="btn btn-sm" onclick="openImagePicker('value-<?php echo esc($k); ?>','preview-<?php echo esc($k); ?>')">Pick existing</button>
            </div>
          </label></div>
          <div id="preview-<?php echo esc($k); ?>" style="margin-top:6px">
            <?php if (!empty($localVal)): ?>
              <img src="<?php echo asset($localVal); ?>" style="max-width:100%;height:60px;object-fit:cover">
            <?php endif; ?>
          </div>
          <div style="margin-top:6px"><button type="submit">Save Path</button> <a href="?">Reset</a></div>
        </form>
      </div>
    <?php endforeach; ?>
  </div>

  <p style="margin-top:12px"><a href="dashboard.php">Back to Dashboard</a></p>
</div>

<?php require_once __DIR__ . '/partials/footer.php'; ?>
<?php // Include the shared image picker modal so admins can choose registered images
require_once __DIR__ . '/partials/image_picker.php'; ?>
